application: your_application_id
runtime: python27
api_version: 1
version: 1
threadsafe: true


handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
